version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase

  - package-ecosystem: "maven"
    directory: "/AvoinDataCommon"
    schedule:
      interval: "daily"
    versioning-strategy: increase

  - package-ecosystem: "maven"
    directory: "/AvoinDataServer"
    schedule:
      interval: "daily"
    versioning-strategy: increase

  - package-ecosystem: "maven"
    directory: "/AvoinDataUpdater"
    schedule:
      interval: "daily"
    versioning-strategy: increase

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"