ALTER TABLE composition
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;

ALTER TABLE composition_time_table_row
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;

ALTER TABLE journey_section
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;

ALTER TABLE locomotive
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;

ALTER TABLE operator
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;

ALTER TABLE operator_train_number
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;

ALTER TABLE station
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;

ALTER TABLE system_state_property
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;

ALTER TABLE time_table_row
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;

ALTER TABLE train
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;

ALTER TABLE train_category
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;

ALTER TABLE train_type
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;

ALTER TABLE wagon
    ADD created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ALGORITHM=INSTANT,
    ADD modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, ALGORITHM=INSTANT;
