name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Compile
        run: mvn -f pom.xml -T1.5C install -e -U -DskipTests=true -Ddependency-check.skip=true
      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: FAILED Rail build
          fields: repo, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
