name: Dependency check
on:
  push:
    branches: [master]
  schedule:
    - cron: '0 8 * * *' # UTC
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
          cache: maven
      - name: Dependency check
        run: mvn dependency-check:aggregate
      - name: Upload report
        uses: actions/upload-artifact@v3
        if: ${{ success() | failure() }}
        with:
          name: dependency-check-report.html
          path: |
            AvoinDataCommon/target/dependency-check-report.html
            AvoinDataServer/target/dependency-check-report.html
            AvoinDataUpdater/target/dependency-check-report.html
      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: FAILED Rail Dependency Check
          fields: repo, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
