name: Dependency check
on:
  push:
    branches: [master]
  schedule:
    - cron: '0 8 * * *' # UTC
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
          cache: maven
      - name: Cache dependency-check files
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository/org/owasp
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-dependency-check-
      - name: Dependency check
        run: mvn dependency-check:aggregate
      - name: Upload report
        uses: actions/upload-artifact@v3
        if: ${{ success() || failure() }}
        with:
          name: dependency-check-report.html
          path: target/dependency-check-report.html
      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: FAILED Rail Dependency Check
          fields: repo, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
