name: 'S3 poll'
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: environment
        default: 'beta'
      bucket-name:
        description: 'Bucket name'
        required: true
        type: string

jobs:
  update_applications:
    environment: ${{ github.event.inputs.env }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.S3_ROLE }}
          role-session-name: gh-actions-deploy-rail-${{ github.event.inputs.env }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Get version files from S3
        run: |
          aws s3 sync s3://${{ github.event.inputs.bucket-name }} .
        shell: bash
      - name: Set schema versions
        id: versions
        run: |
          test -f etj2_${{ github.event.inputs.env }}.imported && echo "etj2=$(cat etj2_${{ github.event.inputs.env }}.imported|cut -d'_' -f 3)" >> $GITHUB_OUTPUT
          test -f infra_${{ github.event.inputs.env }}.imported && echo "infra=$(cat infra_${{ github.event.inputs.env }}.imported|cut -d'_' -f 3)" >> $GITHUB_OUTPUT
          
          # to reset exit code
          echo "Versions are set"
        shell: bash
      - name: Checkout
        if: ${{ steps.versions.outputs.infra || steps.versions.outputs.etj2 }}
        uses: actions/checkout@v3
      - name: Update etj2-api
        if: ${{ steps.versions.outputs.etj2 }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo updating etj2-api to version ${{ steps.versions.outputs.etj2 }}
          gh workflow run deploy-from-repo.yml -f env=${{ github.event.inputs.env }} -f application-name=etj2-api -f config-branch=master -f suffix=${{ steps.versions.outputs.etj2 }}
          aws s3 rm s3://${{ github.event.inputs.bucket-name }}/etj2_${{ github.event.inputs.env }}.imported
        shell: bash
      - name: Update infra-api
        if: ${{ steps.versions.outputs.infra }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo updating infra-api to version ${{ steps.versions.outputs.infra }}
          gh workflow run deploy-from-repo.yml -f env=${{ github.event.inputs.env }} -f application-name=infra-api -f config-branch=master -f suffix=${{ steps.versions.outputs.infra }}
          aws s3 rm s3://${{ github.event.inputs.bucket-name }}/infra_${{ github.event.inputs.env }}.imported
        shell: bash
        