name: 'S3 poll'
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: environment
        default: 'beta'
      bucket-name:
        description: 'Bucket name'
        required: true
        type: string

jobs:
  check_bucket:
    environment: ${{ github.event.inputs.env }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.S3_ROLE }}
          role-session-name: gh-actions-deploy-rail-${{ github.event.inputs.env }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Check bucket
        run: |
          aws s3 ls s3://${{ github.event.inputs.bucket-name }}
        shell: bash
      - name: Get version files from S3
        run: |
          mkdir imported
          aws s3 cp s3://${{ github.event.inputs.bucket-name }}/ ./imported
          ls -lha
          ls -lha imported
        shell: bash
      - name: Get etj2 schema version
        id: etj2_schema_version
        run: |          
          # set version from file to output
          echo "schema_version=$((cat imported/etj2_*.imported|cut -d'_' -f 3))" >> $GITHUB_OUTPUT
        shell: bash
      - name: Get infra schema version
        id: infra_schema_version
        run: |
          # set version from file to output
          echo "schema_version=$((cat imported/infra_*.imported|cut -d'_' -f 3))" >> $GITHUB_OUTPUT
        shell: bash
      - name: Update etj2-api
        run: |
          echo updating etj2-api to version ${{ steps.etj2_schema_version.outputs.schema_version }}
        shell: bash
      - name: Update infra-api
        run: |
          echo updating infra-api to version ${{ steps.infra_schema_version.outputs.schema_version }}
        shell: bash