name: 'S3 poll'
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: environment
        default: 'beta'
      bucket-name:
        description: 'Bucket name'
        required: true
        type: string

jobs:
  check_bucket:
    environment: ${{ github.event.inputs.env }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.S3_ROLE }}
          role-session-name: gh-actions-deploy-rail-${{ github.event.inputs.env }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Check bucket
        id: revision
        run: |
          aws s3 ls s3://${{ github.event.inputs.bucket-name }}
        shell: bash